services:
  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: schema-registry-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2183:2181"  # Different port to avoid conflicts

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: schema-registry-kafka
    depends_on:
      - zookeeper
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095,PLAINTEXT_INTERNAL://kafka:29095
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9095,PLAINTEXT_INTERNAL://0.0.0.0:29095
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  # Schema Registry
  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"  # Schema Registry REST API
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29095'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: schema-registry-kafka-ui
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8083:8080"  # Different port
    environment:
      KAFKA_CLUSTERS_0_NAME: schema-registry-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29095
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

